idci_exporter:
    api_route: "/api/{entity_reference}.{_format}"
    entities:
        schedule_event:
            class: "IDCI\\Bundle\\SimpleScheduleBundle\\Entity\\Event"
            formats:
                jsonp:
                    transformer:
#                        service: "idci_exporter.transformer_twig"
                        options:
#                            template_path:
                            template_name_format: "export.json.twig"

        schedule_category:
            class: "IDCI\\Bundle\\SimpleScheduleBundle\\Entity\\Category"
            formats:
                jsonp:
                    transformer:
#                        service: "idci_exporter.transformer_twig"
                        options:
#                            template_path:
                            template_name_format: "export.json.twig"

        schedule_location:
            class: "IDCI\\Bundle\\SimpleScheduleBundle\\Entity\\Location"
            formats:
                jsonp:
                    transformer:
#                        service: "idci_exporter.transformer_twig"
                        options:
#                            template_path:
                            template_name_format: "export.json.twig"

        schedule_xproperty:
            class: "IDCI\\Bundle\\SimpleScheduleBundle\\Entity\\XProperty"
            formats:
                jsonp:
                    transformer:
#                        service: "idci_exporter.transformer_twig"
                        options:
#                            template_path:
                            template_name_format: "export.json.twig"
